project:
  type: website

website:
  description: "A blog built with Quarto"
  # Update if your GitHub repo isn't named "blog" or your username differs.
  site-url: https://jujuliaa12.github.io/blog/
  title: "myblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jujuliaa12
      # 填上真實網址後把註解取消
      # - icon: bluesky
      #   href: https://bsky.app/profile/你的帳號
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



